### ISSUE TITLE
Error while running SolidBin

### ISSUE THREAD

**Issue by pbravakos** [sufforest/SolidBin#11]
Hi,
I am getting the following error when running SolidBin
```
2020-11-19 12:54:45,319 - Input arguments:
2020-11-19 12:54:45,320 - contig_file:  /mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/OSD100_MegaHIT_KrakenUniqNoCont.fasta
2020-11-19 12:54:45,320 - coverage_profiles:    /mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/OSD100_MegaHIT_SolidBin_coverage.tsv
2020-11-19 12:54:45,320 - composition_profiles: /mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/kmer_4_f1000.csv
2020-11-19 12:54:45,320 - output path:  /mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/OSD100_MegaHIT_SolidBin_result.tsv
2020-11-19 12:54:45,320 - priori_ml_list:       Not Available
2020-11-19 12:54:45,320 - priori_cl_list:       Not Available
2020-11-19 12:54:45,320 - clusters:     Auto
Traceback (most recent call last):
  File "SolidBin.py", line 721, in <module>
    X_t, namelist, mapObj = gen_X(com_file, cov_file)
  File "SolidBin.py", line 58, in gen_X
    cov = cov.apply(lambda x: x+1e-5)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 4152, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 4248, in _apply_standard
    results[i] = func(v)
  File "SolidBin.py", line 58, in <lambda>
    cov = cov.apply(lambda x: x+1e-5)
  File "/usr/lib/python2.7/dist-packages/pandas/core/ops.py", line 715, in wrapper
    result = wrap_results(safe_na_op(lvalues, rvalues))
  File "/usr/lib/python2.7/dist-packages/pandas/core/ops.py", line 686, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas/src/algos_common_helper.pxi", line 1176, in pandas.algos.arrmap_object (pandas/algos.c:46681)
  File "/usr/lib/python2.7/dist-packages/pandas/core/ops.py", line 686, in <lambda>
    lambda x: op(x, rvalues))
TypeError: ("cannot concatenate 'str' and 'float' objects", u'occurred at index contig,/mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/OSD100_AWOSD_PE_MegaHIT,/mnt/scratch/pbravakos/OSD/SolidBin/OSD10
0/MegaHIT/OSD100_CAOSD_PE_MegaHIT,/mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/OSD100_CBOSD_PE_MegaHIT,/mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/OSD100_CCOSD_PE_MegaHIT,/mnt/scratch/pbrava
kos/OSD/SolidBin/OSD100/MegaHIT/OSD100_CDOSD_PE_MegaHIT,/mnt/scratch/pbravakos/OSD/SolidBin/OSD100/MegaHIT/OSD100_DDOSD_PE_MegaHIT')
```
Do you have any suggestions?
Thanks

**Comment by pbravakos** [comment]
I think I found what was causing the error. I had to change all commas in the coverage file to tab characters. I am not sure if this is a bug of the Collate.pl  program, or if i haven't followed the instructions to the letter.
Thanks

**Comment by ziyewang** [comment]
Hi, the separator in the coverage file should be tab characters in the coverage file like some other binners. I will state this in the READme. Thanks.
