### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0, 136)) while a minimum of 1 is required.

### ISSUE THREAD

**Issue by houjialin** [sufforest/SolidBin#12]
Dear Dr. Wang, I met the following error when I trying to run SolidBin with my data. Would you give me any suggestions?  

```shell
2021-01-10 20:38:16,017 - Input arguments:
 16 2021-01-10 20:38:16,017 - contig_file:  ../../2_Assemble/megahit/final.contigs.fa
 17 2021-01-10 20:38:16,017 - coverage_profiles:    SolidBin_coverage_multi_samples.txt
 18 2021-01-10 20:38:16,017 - composition_profiles: ./kmer_4_f10000.csv
 19 2021-01-10 20:38:16,017 - output path:  Results.tsv
 20 2021-01-10 20:38:16,017 - priori_ml_list:   Not Available
 21 2021-01-10 20:38:16,018 - priori_cl_list:   Not Available
 22 2021-01-10 20:38:16,018 - clusters: Auto
 23 2021-01-10 20:38:53,201 - Start generating affinity matrix
 24 Traceback (most recent call last):
 25   File "/home/software/SolidBin/SolidBin.py", line 730, in <module>
 26     affinity_mat = gen_knn_affinity_graph(X_t)
 27   File "/home/software/SolidBin/SolidBin.py", line 44, in gen_knn_affinity_graph
 28     n_jobs=-1)
 29   File "/home/software/miniconda2/envs/solidbin/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
 30     return f(**kwargs)
 31   File "/home/software/miniconda2/envs/solidbin/lib/python3.7/site-packages/sklearn/neighbors/_graph.py", line 109, in kneighbors_graph
 32     metric_params=metric_params, n_jobs=n_jobs).fit(X)
 33   File "/home/software/miniconda2/envs/solidbin/lib/python3.7/site-packages/sklearn/neighbors/_base.py", line 1173, in fit
 34     return self._fit(X)
 35   File "/home/software/miniconda2/envs/solidbin/lib/python3.7/site-packages/sklearn/neighbors/_base.py", line 401, in _fit
 36     X = self._validate_data(X, accept_sparse='csr')
 37   File "/home/software/miniconda2/envs/solidbin/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
 38     X = check_array(X, **check_params)
 39   File "/home/software/miniconda2/envs/solidbin/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
 40     return f(**kwargs)
 41   File "/home/software/miniconda2/envs/solidbin/lib/python3.7/site-packages/sklearn/utils/validation.py", line 653, in check_array
 42     context))
 43 ValueError: Found array with 0 sample(s) (shape=(0, 136)) while a minimum of 1 is required.
```

**Comment by ziyewang** [comment]
It seems that there is something wrong with your input coverage_file. The separator in the coverage file should be tab characters. And the contigs' names in the coverage file should be consistent with those in the kmer_file.  Hope it helps.

Best,
Ziye
